name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Build binary
        run: make build

      - name: Verify binary
        run: |
          ./bin/flickr --help
          echo "✅ Binary built successfully"

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Run unit tests
        run: make test-fast

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella
        continue-on-error: true

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Verify Docker
        run: |
          docker --version
          docker run --rm hello-world

      - name: Run integration tests
        run: make test-integration
        continue-on-error: true # Integration tests may be flaky

  cross-compile:
    name: Cross Compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Build for ${{ matrix.os }}-${{ matrix.arch }}
        run: |
          make build-${{ matrix.os }}-${{ matrix.arch }}
          echo "✅ Successfully built for ${{ matrix.os }}-${{ matrix.arch }}"

      - name: Verify binary info
        run: |
          file ./release/${{ matrix.os }}-${{ matrix.arch }}/flickr
          ls -lh ./release/${{ matrix.os }}-${{ matrix.arch }}/flickr