name: PR

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: read

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest
    name: Lint PR Title
    steps:
      - name: Validate PR Title
        run: |
          PR_TITLE=$(jq -r '.pull_request.title' "$GITHUB_EVENT_PATH")
          echo "PR title: $PR_TITLE"

          # Define the valid pattern (supports conventional commit format)
          if [[ ! "$PR_TITLE" =~ ^(feat|fix|chore|docs|refactor|test|style|ci|perf|build|revert)(\(.*?\))?:\ .* ]]; then
            echo "❌ Invalid PR title: '$PR_TITLE'"
            echo ""
            echo "Expected format: 'type: description' or 'type(scope): description'"
            echo ""
            echo "Allowed types:"
            echo "  - feat: A new feature"
            echo "  - fix: A bug fix"
            echo "  - docs: Documentation only changes"
            echo "  - style: Code style changes (formatting, etc)"
            echo "  - refactor: Code refactoring"
            echo "  - test: Adding or updating tests"
            echo "  - chore: Maintenance tasks"
            echo "  - ci: CI/CD changes"
            echo "  - perf: Performance improvements"
            echo "  - build: Build system changes"
            echo "  - revert: Revert a previous commit"
            echo ""
            echo "Examples:"
            echo "  - feat: add support for multi-artifact releases"
            echo "  - fix(docker): handle empty registry field"
            echo "  - docs: update installation instructions"
            exit 1
          fi

          echo "✅ PR title is valid"